# Generated by Django 5.2.1 on 2025-06-12 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodesEl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=300, null=True)),
                ('description', models.TextField(max_length=1400, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='treeWatcher.nodesel', verbose_name='parent')),
            ],
        ),
    ]
