# Generated by Django 5.2.1 on 2025-06-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesel',
            name='parent',
        ),
        migrations.AddField(
            model_name='nodesel',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='treeWatcher.nodesel', verbose_name='parentId'),
        ),
    ]
