# Generated by Django 5.2.1 on 2025-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0002_remove_nodesel_parent_nodesel_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesel',
            name='amount',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
