# Generated by Django 5.2.1 on 2025-06-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0003_alter_nodesel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesel',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childrens', to='treeWatcher.nodesel', verbose_name='parentId'),
        ),
    ]
