# Generated by Django 5.2.1 on 2025-06-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0004_alter_nodesel_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesel',
            name='isDeleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='nodesel',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='treeWatcher.nodesel', verbose_name='parentId'),
        ),
    ]
