# Generated by Django 5.2.1 on 2025-07-20 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0005_nodesel_isdeleted_alter_nodesel_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=300, null=True)),
                ('orderValue', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nodesel',
            name='description',
        ),
        migrations.AddField(
            model_name='nodesel',
            name='chosenItem',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nodesel',
            name='itemGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treeWatcher.itemgroups', verbose_name='ItemGroup'),
        ),
    ]
