# Generated by Django 5.2.1 on 2025-07-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0006_itemgroups_remove_nodesel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesel',
            name='itemGroup',
        ),
        migrations.AddField(
            model_name='nodesel',
            name='itemGroupId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treeWatcher.itemgroups', verbose_name='ItemGroupId'),
        ),
    ]
