# Generated by Django 5.2.1 on 2025-07-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0007_remove_nodesel_itemgroup_nodesel_itemgroupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=300, null=True)),
                ('price', models.IntegerField(max_length=10, null=True)),
                ('measureUnit', models.IntegerField(max_length=10, null=True)),
                ('orderValue', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nodesel',
            name='ItemUnitId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treeWatcher.itemunit', verbose_name='ItemUnitId'),
        ),
    ]
