# Generated by Django 5.2.1 on 2025-07-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0008_itemunit_nodesel_itemunitid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesel',
            name='chosenItem',
        ),
        migrations.AddField(
            model_name='nodesel',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
