# Generated by Django 5.2.1 on 2025-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0009_remove_nodesel_chosenitem_nodesel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesel',
            name='price',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
