# Generated by Django 5.2.1 on 2025-07-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0010_alter_nodesel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesel',
            name='isPriceFixed',
            field=models.BooleanField(null=True),
        ),
    ]
