# Generated by Django 5.2.1 on 2025-08-16 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeWatcher', '0011_nodesel_ispricefixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemunit',
            name='dependence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='treeWatcher.itemgroups', verbose_name='category'),
        ),
    ]
