# Generated by Django 4.1.13 on 2025-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.CharField(max_length=20),
        ),
    ]
