# Generated by Django 4.1.13 on 2025-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0002_alter_message_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='CO2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='message',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='message',
            name='uuid',
        ),
        migrations.AddField(
            model_name='message',
            name='msg_text',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
